#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Apr 23 11:02:29 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class CFilteredListFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CFilteredListFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self._lstItems = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_AUTOARRANGE|wx.LC_NO_HEADER|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self._txtFilter = wx.TextCtrl(self, -1, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.OnLbButtonDown, self._lstItems)
        self.Bind(wx.EVT_LIST_KEY_DOWN, self.OnLbKeyDown, self._lstItems)
        self.Bind(wx.EVT_LIST_ITEM_MIDDLE_CLICK, self.OnLbButtonDown, self._lstItems)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CFilteredListFrame.__set_properties
        self.SetTitle("Filtered List")
        self._lstItems.SetMinSize((300, 200))
        self._txtFilter.SetMinSize((120, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CFilteredListFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self._lstItems, 1, wx.ALL|wx.EXPAND, 4)
        sizer_3.Add(self._txtFilter, 0, wx.ALL, 4)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def OnLbButtonDown(self, event): # wxGlade: CFilteredListFrame.<event_handler>
        print "Event handler `OnLbButtonDown' not implemented"
        event.Skip()

    def OnLbKeyDown(self, event): # wxGlade: CFilteredListFrame.<event_handler>
        print "Event handler `OnLbKeyDown' not implemented"
        event.Skip()
# end of class CFilteredListFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    fltlist_frame = CFilteredListFrame(None, -1, "")
    app.SetTopWindow(fltlist_frame)
    fltlist_frame.Show()
    app.MainLoop()
